# Generated by Django 5.0 on 2023-12-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_img", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="title",
        ),
    ]
