# Generated by Django 5.0 on 2023-12-25 09:49

import id_img.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_img", "0002_remove_mymodel_creation_date_remove_mymodel_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_num", models.CharField(max_length=13)),
                ("prefix", models.CharField(max_length=256)),
                ("firstName", models.CharField(max_length=256)),
                ("lastName", models.CharField(max_length=256)),
                ("dateOfBirth", models.CharField(max_length=256)),
                ("issueDate", models.CharField(max_length=256)),
                ("expiryDate", models.CharField(max_length=256)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=id_img.models.upload_to
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
