# Generated by Django 5.0 on 2023-12-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_img", "0003_ocrrecord_delete_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrrecord",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
