# Generated by Django 5.0 on 2023-12-25 10:34

import id_img.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_img", "0004_alter_ocrrecord_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=id_img.models.upload_to
                    ),
                ),
            ],
        ),
    ]
