# Generated by Django 5.0 on 2023-12-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id_img", "0005_mymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrrecord",
            name="image_url",
        ),
    ]
